require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItemCardapiosController do

  # This should return the minimal set of attributes required to create a valid
  # ItemCardapio. As you add validations to ItemCardapio, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItemCardapiosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all item_cardapios as @item_cardapios" do
      item_cardapio = ItemCardapio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:item_cardapios).should eq([item_cardapio])
    end
  end

  describe "GET show" do
    it "assigns the requested item_cardapio as @item_cardapio" do
      item_cardapio = ItemCardapio.create! valid_attributes
      get :show, {:id => item_cardapio.to_param}, valid_session
      assigns(:item_cardapio).should eq(item_cardapio)
    end
  end

  describe "GET new" do
    it "assigns a new item_cardapio as @item_cardapio" do
      get :new, {}, valid_session
      assigns(:item_cardapio).should be_a_new(ItemCardapio)
    end
  end

  describe "GET edit" do
    it "assigns the requested item_cardapio as @item_cardapio" do
      item_cardapio = ItemCardapio.create! valid_attributes
      get :edit, {:id => item_cardapio.to_param}, valid_session
      assigns(:item_cardapio).should eq(item_cardapio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItemCardapio" do
        expect {
          post :create, {:item_cardapio => valid_attributes}, valid_session
        }.to change(ItemCardapio, :count).by(1)
      end

      it "assigns a newly created item_cardapio as @item_cardapio" do
        post :create, {:item_cardapio => valid_attributes}, valid_session
        assigns(:item_cardapio).should be_a(ItemCardapio)
        assigns(:item_cardapio).should be_persisted
      end

      it "redirects to the created item_cardapio" do
        post :create, {:item_cardapio => valid_attributes}, valid_session
        response.should redirect_to(ItemCardapio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved item_cardapio as @item_cardapio" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemCardapio.any_instance.stub(:save).and_return(false)
        post :create, {:item_cardapio => {}}, valid_session
        assigns(:item_cardapio).should be_a_new(ItemCardapio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItemCardapio.any_instance.stub(:save).and_return(false)
        post :create, {:item_cardapio => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested item_cardapio" do
        item_cardapio = ItemCardapio.create! valid_attributes
        # Assuming there are no other item_cardapios in the database, this
        # specifies that the ItemCardapio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItemCardapio.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => item_cardapio.to_param, :item_cardapio => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested item_cardapio as @item_cardapio" do
        item_cardapio = ItemCardapio.create! valid_attributes
        put :update, {:id => item_cardapio.to_param, :item_cardapio => valid_attributes}, valid_session
        assigns(:item_cardapio).should eq(item_cardapio)
      end

      it "redirects to the item_cardapio" do
        item_cardapio = ItemCardapio.create! valid_attributes
        put :update, {:id => item_cardapio.to_param, :item_cardapio => valid_attributes}, valid_session
        response.should redirect_to(item_cardapio)
      end
    end

    describe "with invalid params" do
      it "assigns the item_cardapio as @item_cardapio" do
        item_cardapio = ItemCardapio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemCardapio.any_instance.stub(:save).and_return(false)
        put :update, {:id => item_cardapio.to_param, :item_cardapio => {}}, valid_session
        assigns(:item_cardapio).should eq(item_cardapio)
      end

      it "re-renders the 'edit' template" do
        item_cardapio = ItemCardapio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItemCardapio.any_instance.stub(:save).and_return(false)
        put :update, {:id => item_cardapio.to_param, :item_cardapio => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested item_cardapio" do
      item_cardapio = ItemCardapio.create! valid_attributes
      expect {
        delete :destroy, {:id => item_cardapio.to_param}, valid_session
      }.to change(ItemCardapio, :count).by(-1)
    end

    it "redirects to the item_cardapios list" do
      item_cardapio = ItemCardapio.create! valid_attributes
      delete :destroy, {:id => item_cardapio.to_param}, valid_session
      response.should redirect_to(item_cardapios_url)
    end
  end

end
